### ISSUE TITLE
Compare with unity

### ISSUE THREAD

**Issue by j209** [vsg-dev/VulkanSceneGraph#127]
Hi
what is difference between vulcanscenegraph and unreal?

**Comment by openscenegraph** [comment]
The VulkanSceneGraph is an an open source scene graph implemented with C++17 and Vulkan.  It's very much focused in scope and size than either Unity or Unreal - it's not a full game engine, nor has all the game creation tools they have like these have.

The VulkanSceneGraph is a middleware that sits between the low level graphics API and the application/game engine level.  It's general purpose rather than focused on particular market segments like a game engine will be.  It doesn't directly compete with high level APIs and tools, instead it's something that you would use as a component of a high level API/tool.

The VulkanSceneGraph is still in development, we haven't hit 1.0 yet, so the API and implement is still evolving.  If you want a mature tool then you'll need to wait a little while for us to complete the API and implementation.  We are a few months off a beta.

If are willing to live on the bleeding edge, accept rough edges and roll your sleeves up to help refine the AP and implementation then project may well be more useful to you as you can help shape it into what meets your project requirements better than a well established tool that has relatively fixed features and ways of working.
