### ISSUE TITLE
Text.cpp and ShaderSet.cpp includes ".cpp" files from src directory

### ISSUE THREAD

**Issue by artem-korolev** [vsg-dev/VulkanSceneGraph#1322]
**Describe the bug**
I found one place in source code, that might be improved, because it contradicts with code design guidance described here - https://vsg-dev.github.io/vsgTutorial/SettingTheScene/VulkanSceneGraphLibrary

There are two directories:
src/vsg/utils/shaders
src/vsg/text/shaders

Both directories contain .cpp files. The problem is that all of these cpp files are included with "include" directive in other .cpp sources. It looks like this:

```cpp
src/vsg/text/Text.cpp:
...
#include "shaders/text_ShaderSet.cpp"
...

src/vsg/utils/ShaderSet.cpp:
...
#include "shaders/flat_ShaderSet.cpp"
#include "shaders/pbr_ShaderSet.cpp"
#include "shaders/phong_ShaderSet.cpp"
...
```

which is quite greasy solution. It is clear that it is quite easy to fix and make code clean and follow project guidance and best practices in general. If this shaders need to be compiled separately, as I see in Cmake config, then relevant .cpp files should be created for this

**To Reproduce**
No need to reproduce

**Expected behavior**
include ".h" headers from "include" directory as it should be and compile ".cpp" sources in "src", do not include ".cpp" from src directory

**Additional context**
This problem appears right now only in two files (`src/vsg/text/Text.cpp` and `src/vsg/utils/ShaderSet.cpp`), so I believe it is better to solve it sooner, then later.

**Comment by robertosfield** [comment]
Sorry but this opinion is just stupid and confuses the concept of headers and implementations completely.

The shader .cpp are source files that provide the implementation, not headers that declare the interface.  It makes no sense to declare implementations are headers with a .h.

The interfaces are found in include/ directories and have extensions .h, it really is very simple and consistent.

**Comment by artem-korolev** [comment]
No no. i didn't say, you should move implementation to "include" directory. Just including ".cpp" file in another ".cpp" file looks strange and looks like a hack, when someone just don't want to make things clean. and there is only two places in the whole codebase, which proves, that this is just unusual.

**Comment by robertosfield** [comment]
Shaders that are created by external tools are an exception.  It's very much an special case so of course it won't be seen everywhere.  The .cpp shader files are generated by the vsgshaderset utility.

**Comment by AnyOldName3** [comment]
The VSG isn't the only project to embed files like this, but it *is* the only place I've seen it done by having a separate `.cpp` file that gets `#include`d. Some more conventional approaches are:
* Putting the generated code directly into the source file. Obviously this isn't appropriate here as it's not a one-off, so manual copying and pasting is too much hassle.
* Generating a `.cpp` file and linking with it normally, and also generating a header that declares what's in the `.cpp` (or if it's just one symbol, printing it and then copying and pasting it into a source file).
* Using a `.inl` file extension instead of `.cpp`.
* Using C23's `#embed` (which is available to some of the compilers that the VSG can be built with, but not all of them, especially in C++ mode, so isn't a viable option here).

**Comment by robertosfield** [comment]
Using .ini rather than .cpp doesn't solve an actual problem, it just appeases a coder who has descended to get hung up on something because he is fixated on #include only being using .h.

If there is ever an actual issue with the the use of .cpp then we'll stick with it.
