### ISSUE TITLE
Crashes on macOS `10.14.6` using LunarG SDK`1.2.131.2`

### ISSUE THREAD

**Issue by olegded** [vsg-dev/VulkanSceneGraph#137]
1. Clean checkout and build of the `vsg` library and `vsg` examples
2. Setting up everything as described here https://github.com/vsg-dev/VulkanSceneGraph/blob/master/INSTALL.md#detailed-instructions-for-setting-up-your-environment-and-building-for-macos

###############################
3. Starting `vsgdraw`
Result: crash in
```c++
_rayTracingProperties = getProperties<VkPhysicalDeviceRayTracingPropertiesNV, VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_PROPERTIES_NV>();
``` 
<img width="1341" alt="Screenshot 2020-02-08 at 22 34 58" src="https://user-images.githubusercontent.com/6074172/74092392-56967300-4ac3-11ea-947f-dbf364772c54.png">

Tried to not to query these props by `ifdef`ing or simply commenting out this line (for testing).
Result: crash in with both `queueFamilyIndex` and `queueIndex` equal to `0`
<img width="1350" alt="Screenshot 2020-02-08 at 22 41 50" src="https://user-images.githubusercontent.com/6074172/74092448-4f239980-4ac4-11ea-9f41-e101eabd1e58.png">

In both cases crashes happen in Vulkan SDK functions, further debugging needed.

###############################
4. Starting `vsgcompute`
```bash
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
Compilation failed:

program_source:26:26: error: 'function_constant' has a duplicate index '2'
constant uint _167_tmp [[function_constant(2)]];
                         ^
program_source:24:26: note: duplicate 'function_constant' index '2' here
constant uint _166_tmp [[function_constant(2)]];
                         ^
.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Compute shader function could not be compiled into pipeline. See previous logged error.
Error: vsg::Pipeline::createCompute(...) failed to create VkPipeline.
[1]    20184 segmentation fault  ./vsgcompute -o test.vsgt
```

**Comment by mp3butcher** [comment]
try adding this
l 23 in Physical device 
 std::cout<<"vulkan API version :"<< VK_VERSION_MAJOR( _properties.apiVersion)<<"." <<
       VK_VERSION_MINOR( _properties.apiVersion)<<"." <<
      VK_VERSION_PATCH( _properties.apiVersion)<<std::endl;
  
and give use result as well as driver information

**Comment by vsg-dev** [comment]
Thanks for all the details.

I have moved the rayTracingProperties = getProperties<VkPhysicalDeviceRayTracingPropertiesNV, VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_PROPERTIES_NV>(); from PhysicalDevice.cpp to the RayTracingPipeline.cpp and TraceRays.cpp classes so that it'll only be invoked when using a scene graph that requires ray tracing.

   https://github.com/vsg-dev/VulkanSceneGraph/commit/9da364a848ea2991c2e037e16af4b8d578a7b454

This should hopefully address the Mesa + MacOS issues with this call.  In both these case I think the driver should safely handle a call to get the properties - the drivers should know how what extensions and associated they support and ignore queries for properties they don't support. 

The solution I've gone for is better in terms of keep extension queiries local to code that need it, it's a better approach that keep push extensions into widely used code.

--

The MacOS vsgcompute issue looks to be Driver not handing the SPIR-V compute shader.  Perhaps the original GLSL could be tweaked to tweaked to avoid this issue.

The osgcompute example is based on the 3rd party example:

     https://github.com/Erkaman/vulkan_minimal_compute

It's pretty small and easy to get working so it might be worth trying it out to see if ti works where the VSG doesn't.
