### ISSUE TITLE
remove rtti requirement

### ISSUE THREAD

**Issue by wangii** [vsg-dev/VulkanSceneGraph#161]
Current VSG requires rtti to support constexpr function `type_name`.  However, in lots of organizations such requirement is explicitly forbidden or discouraged, e.g. [Google's C++ guidel](https://google.github.io/styleguide/cppguide.html#Run-Time_Type_Information__RTTI_)

I believe it's possible to remove such `typeid` call in type_name.h without changing the overall design.  Please let me know if I should go ahead and give it a try.

**Comment by robertosfield** [comment]
The typeid is used as a fallback.  If there is improvement that could be made without increasing complexity then please dive in.

As a general comment type_name() is not a feature that will be called on inner loops that will be critical to performance.  Ease of maintenance trumps performance in this case.

**Comment by wangii** [comment]
"fallback" is the part I'm not sure about. how about make `VSG_type_name` for new classes mandatory using static_assert?
```c++
template<typename T>
constexpr const char* type_name() noexcept 
{ 
    static_assert(false, __FUNC__); 
    return ""; 
};
```

**Comment by robertosfield** [comment]
I don't quite get why forcing a definition is required, sure it's ideal that users provide their own, but you only need type_name() is you are implementation serialization or what human readable type_name().

The OSG uses RTTI elsewhere, without certain tasks become pretty awkward, so there isn't going to a case where the use of typeid here is going to suddenly make the VSG compilable without RTTI.

**Comment by robertosfield** [comment]
I've just read through the Google RTTI guidelines linked to above and the usage case in type_name() isn't what they are discussing at all, it's a very distinct usage case where the name of type is required for IO or human readable console output used in debugging, it's not being used for if () else blocks decisions as discussed in the motivations of the Google RTTI.

Elsewhere the VSG extensively uses virtual functions and double dispatch as recommend by the Google RTTI, in all there cases where extensibility, performance, robustness and maintainability favour avoiding RTTI.

I'm pretty happy with the RTTI usage in the VSG, it's used just where it's the useful for the job and not extensively through the code.

**Comment by wangii** [comment]
my concern about the fallback call, `typeinfo::name()`, is that according to the [cpp reference](https://en.cppreference.com/w/cpp/types/type_info/name) :

> Returns an implementation defined null-terminated character string containing the name of the type. No guarantees are given; in particular, the returned string can be identical for several types and change between invocations of the same program. 

it might cause problem when generating tiles on one platform with a different compiler but use them on another.

I agree it's not a big problem though.

**Comment by robertosfield** [comment]
On Fri, 10 Apr 2020 at 18:29, Linan Wang <notifications@github.com> wrote:

> my concern about the fallback call, typeinfo::name(), is that according
> to the cpp reference
> <https://en.cppreference.com/w/cpp/types/type_info/name> :
>
> Returns an implementation defined null-terminated character string
> containing the name of the type. No guarantees are given; in particular,
> the returned string can be identical for several types and change between
> invocations of the same program.
>
> it might cause problem when generating tiles on one platform with a
> different compiler but use them on another.
>
> I agree it's not a big problem though.
>
The problem is an issue for serialization as then you have issues about
portability across platforms.  For debug message just some info is more
useful than non.

If we force users to define the type then type_name() won't work for any
types that aren't written specifically for the VSG.  Right now name
vsg::type_name<std::vector<float>>() gives you a useful value rather than
prevent compilation.

So the issue comes down is it useful enough to leave it with a fallback or
problematic enough that we have to prevent the more general purpose usage.

If it turns out that type_name<> ends up being misued with the assumption
that it'll always provide a serializable format then we'd have to revisit
it.

Personally I err on the assumption that VSG users will be sensible and
won't need protecting from all possible misuse.
