### ISSUE TITLE
Generating mipmaps for compressed images

### ISSUE THREAD

**Issue by anormann1974** [vsg-dev/VulkanSceneGraph#248]
When you load a compressed image, which is not containing any mipmaps, and tries to let vsg create the mipmaps, the operation will fail. With NVidia drivers, it is not possible to blit to a compressed format (do not know about other drivers),

Here is a code snippet, which can be used to detect if blitting is possible:
```
void CopyAndReleaseImage::CopyData::record(CommandBuffer& commandBuffer) const
{
  ...
  // Detect, if the device can blit into the destination format
  VkFormatProperties props;
  const auto physicalDevice = commandBuffer.getDevice()->getPhysicalDevice()->getPhysicalDevice();
  vkGetPhysicalDeviceFormatProperties(physicalDevice, layout.format, &props);
  const bool isBlitPossible = (props.optimalTilingFeatures & VK_FORMAT_FEATURE_BLIT_DST_BIT) > 0;
  ...
}

```
I attached an example file, which is compressed in format VK_FORMAT_BC3_UNORM_BLOCK.

[Default_albedo.zip](https://github.com/vsg-dev/VulkanSceneGraph/files/5893980/Default_albedo.zip)

**Comment by robertosfield** [comment]
Now that I've wrapped up the vsgXchange work I have returned to core VSG topics, so am now looking into this issue.  I downloaded the file and it loads fine with vsgviewer:

    vsgviewer Default_albedo.vsgb

Converting the file to .vsgt I get can see that it's a compress block format:

Root id=1 vsg::block128Array2D
{
  NumUserObjects 0
  Layout 137 16 1 4 4 1 0 -1
  Width 512
  Height 512
  Storage id=0
  Data 255 255 0 0 0 0 0 0 179 132 0 0
   0 0 0 0 255 255 0 0 0 0 0 0

Which is all fine.  My next step is to try and recreate the issue you are seeing as vsgviewer isn't show the problem.  Is the problem one you see when you create a vk::Sampler that requires mipmapping?

**Comment by robertosfield** [comment]
I have added a --mipmapLevels numMipLevels (and --mml) to the vsgviewer example so I could test mipmapping with the supplied format.

   vsgviewer Default_albedo.vsgt --mml 5

What I original saw was a black quad except when zooming close into the quad when the texture (mipmap level 0). due to the CopyAndReleaseImage.cpp not doing blitting to generate the required mipmap levels, leave all levels about 0 unset.

As a default behavior disabling mipmapping is detect the use of block compressed data via vsg::Data::Layout.blockWidth, blockHeight, blockDepth checks if any are > 1.  Disabling the mipmap involves setting theSampler::maxLod to 0 and setting mipmapLevels to 1 in the ImageImage.cpp code.

   @e0969db76129f24e705c8c9789d0019cf7cbb2e2

    https://github.com/vsg-dev/VulkanSceneGraph/commit/e0969db76129f24e705c8c9789d0019cf7cbb2e2
