### ISSUE TITLE
MinGW builds fail with `invalid conversion from 'std::thread::native_handle_type' {aka 'unsigned int'} to 'HANDLE' {aka 'void*'}`

### ISSUE THREAD

**Issue by rhabacker** [vsg-dev/VulkanSceneGraph#324]
**Describe the bug**
Building vsg with MinGW gcc fails with the mentioned error

**To Reproduce**
This issue has been detected at https://build.opensuse.org/package/show/home:rhabacker:branches:games:mingw32/mingw32-libvsg

**Expected behavior**
The build should not fail

**Comment by robertosfield** [comment]
On Thu, 9 Sept 2021 at 09:40, Ralf Habacker ***@***.***>
wrote:

> *Describe the bug*
> Building vsg with MinGW gcc fails with the mentioned error
>
> *To Reproduce*
> This issue has been detected at
> https://build.opensuse.org/package/show/home:rhabacker:branches:games:mingw32/mingw32-libvsg
>

Did you copy and past the description of the page?

"The OpenSceneGraph is an OpenSource, cross platform graphics toolkit for
the development of high performance graphics applications such as flight
simulators, games, virtual reality and scientific visualization. Based
around the concept of a SceneGraph, it provides an object oriented
framework on top of OpenGL freeing the developer from implementing and
optimizing low level graphics calls, and provides many additional utilities
for rapid development of graphics applications."

*Expected behavior*
> The build should not fail
>

Just looking at the changes, a static_cast<> would be better than a C
caster for the thread change.

The change to the template class declaration seems a bit odd, as this isn't
normally what one would do.  It's not immediately obvious what the compile
error is in this instance.

Could you just post the errors directly rather than this other website?

**Comment by rhabacker** [comment]
> Did you copy and past the de

Thanks for pointer, I updated the description.

> Could you just post the errors directly rather than this other website?
```
[  125s] /home/abuild/rpmbuild/BUILD/VulkanSceneGraph-0.1.4.20210909.git+7847d18a/src/vsg/threading/Affinity.cpp: In function 'void vsg::setAffinity(std::thread&, const vsg::Affinity&)':
[  125s] /home/abuild/rpmbuild/BUILD/VulkanSceneGraph-0.1.4.20210909.git+7847d18a/src/vsg/threading/Affinity.cpp:49:43: error: invalid conversion from 'std::thread::native_handle_type' {aka 'unsigned int'} to 'HANDLE' {aka 'void*'} [-fpermissive]
[  125s]    49 |     win32_setAffinity(thread.native_handle(), affinity);
[  125s]       |                       ~~~~~~~~~~~~~~~~~~~~^~
[  125s]       |                                           |
[  125s]       |                                           std::thread::native_handle_type {aka unsigned int}
[  125s] /home/abuild/rpmbuild/BUILD/VulkanSceneGraph-0.1.4.20210909.git+7847d18a/src/vsg/threading/Affinity.cpp:20:38: note:   initializing argument 1 of 'void win32_setAffinity(HANDLE, const vsg::Affinity&)'
[  125s]    20 | static void win32_setAffinity(HANDLE tid, const vsg::Affinity& affinity)
[  125s]       |                               ~~~~~~~^~~
[  125s] make[2]: *** [src/vsg/CMakeFiles/vsg.dir/build.make:1498: src/vsg/CMakeFiles/vsg.dir/threading/Affinity.cpp.obj] Error 1
```
