### ISSUE TITLE
Definition of OS dependant Preprocessor Definitions

### ISSUE THREAD

**Issue by rainergericke** [vsg-dev/VulkanSceneGraph#527]
**Is your feature request related to a problem? Please describe.**
I tried to build vsgSDL under macOS and Windows. Both versions suffer from the same problem:

macOS: compilation breaks due to missing preprocessor symbol VK_USE_PLATFORM_MACOS_MVK

Windows: compilation breaks due to missing preprocessor symbol VK_USE_PLATFORM_WIN32_KHR

vsgSDL also supports Linux, but I don't have it. Does it work for you?

**Describe the solution you'd like**
VSG 'knows' about the OS and could set these rsp. symbols, so that they can be used after including <vsg/all.h>

**Comment by robertosfield** [comment]
I am just heading out but I vaguely recall vsgQt having a code path that has to deal with this so would be worth doing a review to see what it does.

**Comment by robertosfield** [comment]
I just tried vsgSDL under Kubuntu 22.04 and it fails to compile for me due to the over-zealous pramga usage

/home/robert/Dev/vsgSDL/src/vsgSDL/window.cpp: In member function ‘bool vsgSDL::Window::initInstance(std::string, uint32_t, uint32_t, bool, bool)’:
/home/robert/Dev/vsgSDL/src/vsgSDL/window.cpp:70:57: error: invalid use of void expression
   70 |         instanceExtensions.push_back(instanceSurfaceName());
      |                                      ~~~~~~~~~~~~~~~~~~~^~

The same function in vsgQt just uses a C function and works fine.  I see this as a Window specific topic that isn't appropriate for the VSG to control/dictate other than for it's own in-built Windowing functions.  I think it's appropriate to have such functions in vsgQt/vsgSDL.  I'm going to close this PR as it's really not the VSG's place to dictate how 3rd party libraries are managed.
