### ISSUE TITLE
Is Auxiliary* Object::getOrCreateUniqueAuxiliary() thread safe

### ISSUE THREAD

**Issue by timprepscius** [vsg-dev/VulkanSceneGraph#90]
I'm looking at Auxiliary* Object::getOrCreateUniqueAuxiliary()

It doesn't look thread safe to me.  Is it supposed to be?

Also, if getOrCreateUniqueAuxiliary is not thread safe, I'm reasonably sure that _delete becomes not thread safe, and maybe the whole reference counting structure you have set up.

Also, just my unwanted two cents but:
--- BEGIN UNWANTED OPINION ---

void Object::_delete() const
{
    // what should happen when _delete is called on an Object with ref() of zero?  Need to decide whether this buggy application usage should be tested for.

YES!  Put a debug only assert.

AND, it is strange to me that you would have _delete sometimes not delete.  I understand your code- it seems to me that the Auxilary should have *weak_ptr* to the main object, and the object should have a strong_ptr to the auxiliary.  If the auxiliary wants to keep the main object around, it could make a strong_ptr.

Anyhow.

I'm sure you are aware of all the different smart_ptr implementations out there.  Yours of including the reference count in the object.  Std contains one which is nice, not sure if they have weak_ptr- I think they do.  Seems like an obvious choice.

Also, Eberly's Geometric Tools has a pretty nice one.  

--- END UNWANTED OPINION ---

**Comment by vsg-dev** [comment]
The ref_ptr<>/observer_ptr<>/Object classes have been written to be thread safe, note the use of atomics.   If there is a threading bug in there then we'll need to create a test case that flushes it out and resolves it.

Intrusive reference counting is used as scene graphs a memory bandwidth bound so for performance it's critical that object sizes are kept to a minimum so that the cache is most efficiently used.  

The  vsgExamples/Core/vsggroups example has an experiement test path that enables one to compare the VSG's native smart pointers with std::shared_ptr<> based implementation and the confirms that intrusive ref counting is ~25% faster than non intrusive ref counting provided by shared_ptr<>.

The OpenSceneGrah also has intrusive reference counting so we've got plenty of experience of how they work, including debugging the implementation.

**Comment by timprepscius** [comment]
```
Auxiliary* Object::getOrCreateUniqueAuxiliary()
{
    DEBUG_NOTIFY << "Object::getOrCreateUniqueAuxiliary() _auxiliary=" << _auxiliary << std::endl;
    if (!_auxiliary)
    {
        _auxiliary = new Auxiliary(this);
        _auxiliary->ref();
    }
    else
    {


void Object::_delete() const
{
    // what should happen when _delete is called on an Object with ref() of zero?  Need to decide whether this buggy application usage should be tested for.

    // if there is an auxiliary attached signal to it we wish to delete, and give it an opportunity to decide whether a delete is appropriate.
    // if no auxiliary is attached then go straight ahead and delete.
    if (_auxiliary == nullptr || _auxiliary->signalConnectedObjectToBeDeleted())
    {
```
```

1. Object O is created.
2. Object O is dereffed _delete (thread1), while getOrCreateUniqueAuxiliary is called (thread2)

or

1. Object O is created
2. getOrCreateUniqueAuxiliary is called (thread1), getOrCreateUniqueAuxiliary is called(thread2)

In situation 1:
auxiliary is created, has a pointer to this.
auxiliary is the kind which prevents deletion of object
auxiliary will assume that Object O is valid.
because Object O is deleted.

auxiliary is created, has pointer to this
auxiliary is not the kind which prevent deletion
auxiliary is unref'ed before it is ref'ed

In situation 2:
auxiliary is created in both threads.
    if (!_auxiliary) needs to be mutexed.

auxiliary is created in 1 thread
but then
        if (_auxiliary->getConnectedObject() != this)
is entered by thread 2
                _auxiliary = new (ptr) Auxiliary(this, allocator);
is called before thread 1 ref

previousAuxiliary->unref();
is called before ref.

--- BEGIN UNWANTED OPINION ---

If auxiliary wants to prevent deletion, it should have a strong_ptr to the object

if this is not the case
_delete should be renamed to _possibly_delete_but_maybe_not_in_rare_cases

Because anyone reading functions and tracing will think that a function named _delete will delete.

--- END UNWANTED OPINION ---

```

**Comment by vsg-dev** [comment]
Confusing hypotheticals aren't really helpful.  I don't think an Issue tracker is a place for such general pontifications.  If you have a usage case that is actually problematic then please use actual C++ code that illustrates it as it's the most efficient way of conveying a usage case without ambiguity.

As general comment, The Auxiliary objects absolutely can *never* hold a strong pointer to the object that owns it, doing so would create a circular reference and prevent the either the Auxilary or the original Object from ever getting deleted.  So you never ever want the Auxuliary to prevent Object from being deleted.

If you want the Object to be prevent from being deleted then you have to take a reference to the Object, you might use the Auxiliary to get to the Object to take the reference and this is how one would safely access the Object that a weak pointer (vsg::obersver_ptr<>).

As for coming up with names to explain_exactly_what_might_happen_in_all_possible_executation_paths_in_a_method, well it quickly gets pretty silly.  Internal implementation details are things that most users will never need to look it, those who do then comments within the method can explain further when it's not otherwise obviously apparent from the code.

I can't help but feel that you are rather getting off in the minutia of implementation details way too prematurely.  The software is not even close to beta yet, it's in flux, many features are left to write, including multi-threading, when we do get into this then we'll start finding the edges of where things aren't yet multi-thread robust enough yet, when problems arise we'll resolve them.

FYI, in August one of the tasks I'll be getting back to is implement multi-threaded database paging. This will be the first proper stress test on the multi-threading side.  After this is done I'll eventually move to make it possible to mult-threaded cull and command dispatch traversals.  It's all ground I've done extensive work on before with the OpenSceneGraph project so I'm fully aware of the complexities that multi-threading can introduce and techniques we can deploy.  

As we don't have stress cases to test the multi-threading side there isn't much point in pontificating on hypothetical stuff that may or may not have any relevance in the real-world code and applications.  I'm going to close this thread as it's really it just heading off in sand and away from useful work.

**Comment by timprepscius** [comment]
Unfortunately, in my experience, "multi-threading hypothetical" actually means "incredibly difficult bug to find down the road."  Maybe you don't have experience with bugs which happen once out of a thousand runs yet.  They suck.

Yeah.  I don't like code which says, "_delete" but doesn't delete.

Good luck :-)

**Comment by vsg-dev** [comment]
We have decades of experience with developing multi-threaded scene graphs, enough experience to know that you have to get concrete when talking about the type of problems you want to code for. Kicking about pseudo code and hypotheticals is a waste of time, and sarcasm just isn't as clever as you think it is, it just makes you look like someone trying to be more clever than they really are.

If there is a concrete case that is relevant then write a test program that illustrates the usage case and issue and share it.  If there is a real, verifiable problem with the VSG code then we'll investigate and address it.
